export const theme = {
  dark: {
    background: "black",
    title: "white",
    para: "#8993b1",
    heading: "#CCD6F6",
    line: "#24243a",
    imgBackground: "black",
    highlightBackground: "black",
    sideIcons: "#8892b0",
    menuBackground: "black",
    card: "#112240",
    linkHover: "white",
    buttonColor: "black",
  },
  light: {
    buttonColor: "white",
    background: "#FFFFFF",
    title: "black",
    para: "#233742",
    heading: "#233742",
    line: "lightgray",
    imgBackground: "#e9f3e8",
    highlightBackground: "#f0f8ef",
    sideIcons: "#766161",
    menuBackground: "#aaeff8",
    card: "#8BD8CE",
    linkHover: "black",
  },
};
